#!/system/bin/sh
#DISWARN 3.2 script by Kenas for 4PDA.ru

setprop diswarn.PID $$
setprop diswarn.connect 0
setprop diswarn.disconnect 0
	
nohup diswarn_message < /dev/null > /dev/null 2>/dev/null &

logcat -s -T 1 "bt-btif:W" /dev/null | 
while read code1 code2 code3 code4 code5 code6 code7; do 
	if [ "$code4$code5$code6" = "invalidrfcslot" ]; then #device disconnected
		setprop diswarn.disconnect `date +%s`
	elif [ "$code4$code5" = "newconn_srvc" ]; then #device connected
		setprop diswarn.connect `date +%s`
	fi
	
	if [ `getprop diswarn.stop` -eq "1" ]; then #стоп-флаг пользователя
		setprop diswarn.stop 0
		exit
	fi
	if [ `getprop diswarn.PID` -ne $$ ]; then
		exit
	fi
done

setprop diswarn.stopped `date`
