#!/system/bin/sh
# DISWARN 4.0 script by Kenas for 4PDA.ru
# You must specify bluetooth MAC address of your device in diswarn_scenario.txt firstly

setprop diswarn.PID $$
setprop diswarn.connect 0
setprop diswarn.disconnect 0
	
nohup diswarn_message < /dev/null > /dev/null 2>/dev/null &

logcat -s -b main -T 1 "IWDS---b:I" /dev/null | 
while read -r code1 code2 code3 code4 code5 code6 code7 code8 code9; do 
	case $code3$code8 in
	'Disconnect[devAddress='`getprop diswarn.bt_addr`",") setprop diswarn.disconnect `date +%s`;;
	'Connect[devAddress='`getprop diswarn.bt_addr`",") setprop diswarn.connect `date +%s`;;
	esac
	
	if [ `getprop diswarn.stop` -eq "1" ]; then # stop by user command
		setprop diswarn.stop 0
		exit 4
	fi
	if [ `getprop diswarn.PID` -ne $$ ]; then # stop if new one script running
		exit 3
	fi
done

setprop diswarn.stopped `date`
