#!/system/bin/sh
# DISWARN MESSAGE SUB 4.0 script by Kenas for 4PDA.ru
# Enable vibration alerts by connection lost
#  Support vibration scenario file "diswarn_scenario.txt" placed at sdcard root
#
# SOME USEFULL FUNCTIONS
function INIT_PROP {
# init default variables
	setprop diswarn.stop 0
	setprop diswarn.message.PID $1
	setprop diswarn.bt_addr 0
	disconnect_vib=(600 600)
	connect_vib=(600)
	# disconnect_pause=(200 0)
	# connect_pause=(0)
	showmessage=1
	diswarn_connect="Connected to smartphone"
	diswarn_disconnect="Disconnected from smartphone"
	diswarn_warn="Disconnect warning service stopped"
	check_pause=30
	stop_script=0
}
function Show_Message {
	if [ "$showmessage" -ne "0" ]; then # messages activated
		input keyevent KEYCODE_WAKEUP
		sleep 0.5
		am start -a android.intent.action.MAIN -e message "$1" -n com.android.msg/.ShowToast 1>/dev/null 
	fi
}
function Vibrate {
	until [ `cat /sys/class/timed_output/vibrator/enable` -eq 0 ]; do sleep 0.1; done
	echo $1 > /sys/class/timed_output/vibrator/enable; 
	until [ `cat /sys/class/timed_output/vibrator/enable` -eq 0 ]; do sleep 0.1; done
	sleep $2
}
function Read_Scenario {
# some tricks for correct reading Windows text file
	scfile=$(tr -d "\r" < "/mnt/shell/emulated/0/diswarn_scenario.txt") 
	while read -r desc line || [[ -n $line ]]; do
		case $desc in
			"DISCONNECT") disconnect_vib=($line);;
			"CONNECT") connect_vib=($line);;
		#	"CONNECT_PAUSE") connect_pause=( $line );;
		#	"DISCONNECT_PAUSE") disconnect_pause=( $line );;
			"SHOWMESSAGE") showmessage=$line;;
			"CONNECT_TEXT") diswarn_connect=$line;;
			"DISCONNECT_TEXT") diswarn_disconnect=$line;;
			"WARNING_TEXT") diswarn_warn=$line;;
			"DELAY_IN_SEC") check_pause=$line;;
			"BT_ADDR") setprop diswarn.bt_addr $line;;
			"STOP") if [ $line -eq "1" ]; then setprop diswarn.stop 1; fi ;;
		esac
	done <<<  "$scfile"
	
	if [ `getprop diswarn.bt_addr` -eq 0 ]; then #check bt MAC 
		input keyevent KEYCODE_WAKEUP
		sleep 0.5
		am start -a android.intent.action.MAIN -e message "Bluetooth MAC of your smartphone not found. Please edit diswarn_scenario.txt. Diswarn STOPPED" -n com.android.msg/.ShowNotification 1>/dev/null 
		setprop diswarn.stop 1
	fi
}

# BEGIN

INIT_PROP $$ # initialize variables
Read_Scenario # rewrite default variables from diswarn_scenario.txt
check_delay=$check_pause
while 
do
	sleep "$check_delay"
	if [ `getprop diswarn.message.PID` -ne $$ ]; then # stop if new one script running
		exit 3
	fi
	if [ `getprop diswarn.stop` -eq "1" ]; then #stop by user command
		exit 4
	fi
	if [ $check_pause -gt $check_delay ]; then (( check_delay += 1 )); fi #slow down main speed
	dis_time=`getprop diswarn.disconnect`
	con_time=`getprop diswarn.connect`
	if [ $dis_time -gt $con_time ]; then # catch device disconnect
		setprop diswarn.connect 0
		setprop diswarn.disconnect 0
		Read_Scenario
		Show_Message "$diswarn_disconnect"
		for elem in ${disconnect_vib[@]}; do
			Vibrate $elem 0.4
		done
		check_delay=1 # increase main while-done speed waiting for connect
	elif [ $dis_time -eq 0 ] && [ $con_time -gt 0 ]; then
		setprop diswarn.connect 0
		setprop diswarn.disconnect 0
		Read_Scenario
		Show_Message "$diswarn_connect"
		for elem in ${connect_vib[@]}; do
			Vibrate $elem 0.4
		done
		check_delay=$check_pause # set default main while-done latency
	fi
done
input keyevent KEYCODE_WAKEUP
sleep 0.5
am start -a android.intent.action.MAIN -e message "$diswarn_warn" -n com.android.msg/.ShowNotification 1>/dev/null 
Vibrate 300 0.5
Vibrate 300 0.5
Vibrate 300 0.5

setprop diswarn.message.stopped `date`